apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  labels:
    app: frontend
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: podinfo
    helm:
      values: |-
        replicaCount: 2
        backend: http://backend-podinfo:9898/echo
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: 6.2.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
