---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: traefik
    helm:
      values: |-
        service:
          type: LoadBalancer
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.22.0
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true