name: Deploy to Environment

on:
  pull_request:
    types: [opened, closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubectl
        run: kubectl config set-cluster kind-cluster --server=https://127.0.0.1:6443

      - name: Apply changes (Create Environment)
        if: github.event.action != 'closed'
        run: |
          kubectl apply -f argocd/apps/{{ github.head_ref }}/

      - name: Delete Environment
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          kubectl delete namespace {{ github.head_ref }}

