name: Deploy to Environment

on:
  push:
    branches:
      - master
      - 'feature/job-interview-task'

env:
  TF_DIR: terraform/kind

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: set branch name 
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: Set branch name for PR
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF//\//-}" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'

      - name: Terraform Destroy
        run: terraform destroy -var="name=$BRANCH_NAME" -auto-approve
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Apply
        run: |
          terraform apply -var="name=$BRANCH_NAME" -auto-approve
        working-directory: ${{ env.TF_DIR }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          terraform output -raw kubeconfig_path > $HOME/.kube/config
        working-directory: ${{ env.TF_DIR }}

      - name: Deploy environment
        run: |
          mkdir -p argocd/apps/${BRANCH_NAME}
          cp -r argocd/apps/dev argocd/apps/${BRANCH_NAME}
          kubectl apply -R -f argocd/apps/${BRANCH_NAME}/

      - name: Terraform Destroy
        if: ${{ github.event.pull_request.merged }}
        run: terraform destroy -auto-approve
        working-directory: ${{ env.TF_DIR }}

