name: Deploy to Environment

on:
  pull_request:
    types: [opened, closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubectl
        run: kubectl config set-cluster kind-cluster --server=https://127.0.0.1:6443

      - name: Deploy environment
        if: github.event.action != 'closed'
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          cp -r argocd/apps/dev argocd/apps/${BRANCH_NAME}
          kubectl apply -f argocd/apps/${BRANCH_NAME}

      - name: Cleanup environment
        if: github.event.action == 'closed'
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          kubectl delete app ${BRANCH_NAME} -n argocd
          rm -rf argocd/apps/${BRANCH_NAME}

