name: Deploy to Environment

on:
  push:
    branches:
      - master
      - 'feature/job-interview-task'

env:
  TF_DIR: terraform/kind

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Destroy
        run: terraform destroy -var-file=dev.tfvars -auto-approve
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Apply
        run: |
          terraform apply -var-file=dev.tfvars -auto-approve
        working-directory: ${{ env.TF_DIR }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          terraform output -raw kubeconfig > $HOME/.kube/config
        working-directory: ${{ env.TF_DIR }}

      - name: Deploy environment
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          mkdir -p argocd/apps/${BRANCH_NAME}
          cp -r argocd/apps/dev argocd/apps/${BRANCH_NAME}
          kubectl apply -R -f argocd/apps/${BRANCH_NAME}/

      - name: Terraform Destroy
        if: ${{ github.event.pull_request.merged }}
        run: terraform destroy -auto-approve
        working-directory: ${{ env.TF_DIR }}

